name    'puppet-wordpress'
version '0.3.2a'
source 'https://github.com/seattle-biomed/puppet-wordpress'
author 'Atom Powers'
license 'Apache2'
summary 'Puppet module to install wordpress and plugin files.'
description 'Install wordpress and plugins, setup the admin account.'
project_page 'https://github.com/seattle-biomed/puppet-wordpress'
